### ISSUE TITLE
Hook for Startup and Teardown

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#20]
In other "gherkin" implementations there are hooks available for "begin" and "end" of feature file execution.

in cucumber-cpp these are e.g. mapped to "BEFORE_ALL" "AFTER_ALL" macros.

Could these also be added to the defines / steps and how is ensured that AFTER_ALL position independent added to the end of the executions.
These functions should not be called as "tests" just for preparation / teardown e.g.

**Comment by ThoSe1990** [comment]
good call, will keep it in mind for next version

**Comment by ThoSe1990** [comment]
I created 2.1.0: https://github.com/ThoSe1990/cwt-cucumber/releases/tag/2.1.0

Checkout `examples/hooks.cpp` I added `BEFORE_ALL` and `AFTER_ALL` 

I'll close this issue for future findings, just open a new one
