### ISSUE TITLE
How to parse ordinal numbers

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#22]
I want to parse german ordinals as number, a very simple example

```
Then Hat der 1. Eintrag der Liste den Wert 0
And Hat der 2. Eintrag der Liste den Wert 1
```
I cannot capture the ordinals (1., 2.) in the hook, getting always "unmatched"
i tried with "{int}.",  "{word}", {}. Only solution was to get rid of the "dot" or use "erste, zweite, dritte".
Why {} does not match at least? Due to the docs it is not implemented. Right?
Adding in quotes and parse the value from a string is more a workaround.
I thing implementing a {} operator would be sufficient, matching whitespace only around it.

**Comment by ThoSe1990** [comment]
I used the dot as identifier for floating point values, but you're correct this should work as you reported. 

The only workaround now would be to rephrase to `Element at index {int} has value ...`  

I will fix this

**Comment by ThoSe1990** [comment]
hmm, yh I aggree. On the other hand, if you consider the java version where you define steps with regex you can do so. 

I just implemented it, and we'll see if this gets changed. I added an example to `examples/features/1_first_scenario.feature`: 

```
  Scenario: Second Scenario
    Given An empty box
    When I place 1 x "apple" in it
    And I place 1 x "banana" in it
    Then The 1. item is "apple"
    And The 2. item is "banana"
```

where `examples/step_definition.cpp" looks like this: 
```
THEN(test, "The {int} item is {string}")
{
  const std::size_t number = CUKE_ARG(1);
  const std::size_t idx_zero_based = number - 1;
  const std::string item = CUKE_ARG(2);
  
  cuke::equal(item, cuke::context<box>().at(idx_zero_based));
}
```

so leave the dot out of the definition. I'll close this issue when i created another version

**Comment by ThoSe1990** [comment]
I created 2.1.0: https://github.com/ThoSe1990/cwt-cucumber/releases/tag/2.1.0

I'll close this issue for future findings, just open a new one
