### ISSUE TITLE
Check Makros with hint Message

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#27]
when using cuke::is_true or is_false, it should be possible to give a helpfull message as output instead of the default one.
The functions could maybe extended with a second msg parameter (empty default) which could be shown if not empty, else the standard message.

**Comment by ThoSe1990** [comment]
I agree, want to extend the default message or replace it?

**Comment by kreuzberger** [comment]
i would suggest to replace it, but i am not sure what was the intention of the ":" at the end.

**Comment by ThoSe1990** [comment]
The error msg's are printed before the actual step, so at that time i thought it was logical to do so. Since the output is colored i guess it does not matter too much

**Comment by ThoSe1990** [comment]
anyway lets replace it, both messages will clutter the output too much.

**Comment by ThoSe1990** [comment]
Done & merged

 Use all asserts statements with an optional msg like: 
```
cuke::equal(1,2, "this is not equal") ;
cuke::is_false(true, "this is not false"); 
// ... 
```

**Comment by ThoSe1990** [comment]
I'll close this, if anything is still up, open a new issue
