### ISSUE TITLE
STEP DELAY Feature

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#30]
If defined the steps should be delayed with a given timeout. This sometimes make step execution "visible" for people who want to see / follow whats going on. This is often the case in UI tests i make with customers.

Therefore there should be an environment variable to handle a fixed timeout between each step / scenario etc.
The value should be in ms. The runner should wait the given time after each run.

Suggestion is CWT_CUCUMBER_STEP_DELAY

**Comment by ThoSe1990** [comment]
sure, we can do so. but instead of an environment variable I'd prefer extending the program arguments, so that execution goes like this: 

`./build/bin/box --step-delay 100 ./features/example.feature`
or a short version
`./build/bin/box -d 100 ./features/example.feature`

I can implement this later

**Comment by kreuzberger** [comment]
Or maybe both. Let me explain.

I am testing with cmake/ctest and using only an option would force me to reconfigure my build tree. Depending due "modularization" of the cmake code this could effect one or all tests (e.g. if you wrap the test call in a cmake makro/function). Calling the test like ctest does on commandline to just change the option is mostly impossible due to adaptions on LD_LIBRARY_PATH (shared library dependencies), Test Setup and so on.

Using the environment variable i just can set it in the environment and rerun the test and everything is fine.
