### ISSUE TITLE
Generic expression handler {} should be supported

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#31]
To be flexibel and "compatibel" to other gherkin implementations (currently i  use cucumber-cpp and pytest-bdd-ng, both use regex parsers) a generic expression "{}" should be supported.
This should catch all between one or more whitespaces.
Unlike {word} this should catch all, result should be given as string to implement a custom handler for it.
Example:

```
Then The temperature increases 15°
And The temperature is -5° above the reference
```
THEN(.., "The temperature increases {}")

CUKE_ARG(1) should then return "15°"

In the second example it should return "-5°"

**Comment by kreuzberger** [comment]
Using a generic expression would mean for me that the result is an "copy" of the content an this means string in ANY case.
If i would know what to expect (int) i would and could use {int}.
This is a little bit similar to the "This is the 1. entry " we had with int.
The problem for me here is to get content NOT enclosed in hyphens ({string}). This could be similar to {word}, but what are the boundaries? {word} would also be ok but the expectations here with special characters could be different

Let us use the example from #22

```
Then Hat der 1. Eintrag der Liste den Wert 0
```
```
THEN(_, "Hat der {} Eintrag der Listen den Wert {int}")
```
I would expect "1." as string

```
THEN(_, "Hat der {word}. Eintrag der Listen den Wert {int}")
```
I would expect "1" as string

or if space is only word boundary 
```
THEN(_, "Hat der {word} Eintrag der Listen den Wert {int}")
```
I would expect "1." as string




```
THEN(_, "Hat der {int}. Eintrag der Listen den Wert {int}")
```
I would have expected "1" as int

```
THEN(_, "Hat der {int} Eintrag der Listen den Wert {int}")
```
I get now expected "1" as int

**Comment by kreuzberger** [comment]
After some rethinking i found the "online" example tester from cucumber-expressions:
https://cucumber.github.io/try-cucumber-expressions
To be compatible, i would suggest to implement {word} as whitespace delimited, not "" enclosed string
the {int} from issue #22 has to be "reimplemented" for compatiblity.

**Comment by kreuzberger** [comment]
see https://cucumber.github.io/try-cucumber-expressions/?advanced=0&expression=there+is%2Fare+%7Bint%7D.+flight%28s%29+from+%7Bairport%7D&step=there+are+12.+flights+from+LHR

**Comment by kreuzberger** [comment]
> `{word}` shouldn't be a big deal to implement, because its just any character sequence between whitespaces
:+1:

**Comment by kreuzberger** [comment]
> And `{}` would basically be treated as unquoted string then, right?
Yes, but i see the problem to implement it. Unquoted string yes but could exceed more than one space separated words.
For my actual intention {word} would be sufficient and {int} should behave like shown in the examples.

**Comment by ThoSe1990** [comment]
I'd suggest lets start with `{word}` and think about `{}` at a later point in time

**Comment by ThoSe1990** [comment]
So I spent some time with the implementation, but it's pretty error prone to implement this from scratch. There are a lot of edge cases. Right now I only see a reasonable approach to introduce the regex library here, which should bring more control.

**Comment by kreuzberger** [comment]
That's a good idea. A solid solution should be preferred over a quick hack :+1:

**Comment by ThoSe1990** [comment]
Done. ✅ https://github.com/ThoSe1990/cwt-cucumber/pull/36

I implemented both expressions `{word}` and anonymous `{}`. Both are treated as strings. The anonymous expression is basically an unquoted string. I'll update the examples soon, because I have to update the documentation anyway. But for now, feel free to use it. 

For any findings, please open another issue.

FYI, i noticed german steps on some issues, i also implemented german language, so you can use German keywords too.

**Comment by kreuzberger** [comment]
Tanks for your effort. The German language support is a nice benefit too. 
:1st_place_medal:
