### ISSUE TITLE
Tag Handling and special `@skip` tag

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#34]
The filtering of scenarios and features by tags is a good way.
At this point i have questions / suggestions.

## Feature tags and scenario tags
In the examples there is file 4_tags.feature.
This is a little bit different to the README due to the `@all` feature tag.

If i run with tag `@all` then no `@apple` or `@bananas` test is executed. This is not what i expected, but ok. (expected to run all scenarios of the feature and use tagged features to filter features if run with many files)

I wanted then to run the banana test only so i run `@all and @bananas`. But this does nothing, i have to execute `@all or @bananas"`.

And if i run `@bananas` nothings gets run.

Is this intended in this way? For me it would be more intuitive to run `@all` to use the feature and then the "and" operator to run tagged scenarios in this feature? `@all` to enable the feature file itself and then "and" to enable the tagged scenarios.

if "or" was intended and ok then i do not understand why the only `@bananas` does not work.

## Suggestion for special `@skip`

Some of the frameworks i use have a possiblity to skip scenarios by code.
So it might be helpful to have
```
BEFORE_T(_(), "@skip")
{
  cuke::skip("msg")
}
```
This could apply to features and/or scenarios

## Tagged Examples

Tagging a "Scenario Outline" is reasonable, but what should be achieved by tagging "Examples" like the README says? 
Could i then provide more than one example section to the Scenario Outline? Maybe a test / example / README example may be helpful.

**Comment by ThoSe1990** [comment]
Feature Tags: you're right I messed up the tag inheritance, I'll fix it. 

Default Tags: Let me sleep on that, maybe we can provide default tags at compile time then its up to the developer to introduce them or not. 

Tagged examples: As I found out (JS and python version where my references at point of implementation) it is possible to have multiple `Examples` per `Scenario Outline` and you can tag each. Why it is so? I have no idea. I tried to mimic their implementations. And yes you're right I didn't put this in the docs nor in the readme. 

I'll update this issue at a time when i make some progress

**Comment by kreuzberger** [comment]
> Feature Tags: you're right I messed up the tag inheritance, I'll fix it.
> 
:+1:

> Default Tags: Let me sleep on that, maybe we can provide default tags at compile time then its up to the developer to introduce them or not.
> 
Maybe you understand me wrong: to support the `@skip` tag is just need a cuke::skip function. I think its up to myself to implement the hook to have `@skip` working without providing tags. An alternative would be to run with `-t "not @skip"`

> Tagged examples: As I found out (JS and python version where my references at point of implementation) it is possible to have multiple `Examples` per `Scenario Outline` and you can tag each. Why it is so? I have no idea. I tried to mimic their implementations. And yes you're right I didn't put this in the docs nor in the readme.
> 
Ok, that was absolutely new to me. Cool feature

**Comment by ThoSe1990** [comment]
> Maybe you understand me wrong: to support the `@skip` tag is just need a cuke::skip function. I think its up to myself to implement the hook to have `@skip` working without providing tags. An alternative would be to run with `-t "not @skip"`

I see, lets start with `@skip` (and maybe `@ignore`) i found some references online. 

I'll do each on a separate branch.

**Comment by kreuzberger** [comment]
Ok. Thanks for your support this week, this helped me a lot during evaluation of your project as an replacement for our current cucumber toolchain! Very good and clean project/code!

**Comment by ThoSe1990** [comment]
Thanks a lot, I appreciate this feedback.

**Comment by ThoSe1990** [comment]
Tag inheritance fixed& merged https://github.com/ThoSe1990/cwt-cucumber/pull/35

I'll do the skip function tomorrow or so and when its solved I'll close this Issue.

**Comment by kreuzberger** [comment]
currently the after hooks of the specific skipped scenario do not need to be executed, i currently have no use case for it. But the AFTER_ALL hooks etc should be executed (no scenario specific hooks).

**Comment by ThoSe1990** [comment]
Yes, AFTER_ALL is still called
