### ISSUE TITLE
Steps catalog export

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#47]
Sometimes it could be helpful to have a step catalog available, so that developers could see what @given, @tests implementations could be used during development of feature files.
Due to the "global" registration of all steps this registry could just be "exported" in a computer readable format to create a steps catalog.

This should also include the given types in the step definition so that its clear what the test implementation expects.
Why could this be helpful: The Test feature file writer MAY NOT have access to the code and so this could help him to define feature files, WITHOUT manually searching all existing feature files.

**Comment by ThoSe1990** [comment]
Ideally an LSP would be a great solution. But this would be a separate project then. Maybe, existing cucumber LSP's are compatible? 

Aside from that, with this suggestion, it would be great to generate this during compile time (or script it)

**Comment by ThoSe1990** [comment]
Another possible solution is (this would be the easiest and fastest for now) to produce this at runtime or as a separate target because all information basically available in the internal regestry. The step class holds the data: 

```cpp 
class step
{
 public:
  step(step_callback cb, const std::string& definition)
      : m_callback(cb), m_definition(definition)
// ... 
 private:
  step_callback m_callback;
  std::string m_definition; 
  std::string m_regex_definition;
  std::vector<token_type> m_value_types;
};

```

**Comment by kreuzberger** [comment]
> Ideally an LSP would be a great solution. But this would be a separate project then. Maybe, existing cucumber LSP's are compatible?
> 
> Aside from that, with this suggestion, it would be great to generate this during compile time (or script it)

This is what i also thought about, to parse the step definitions with an extra tool. But then i tought that the internal registry at runtime already holds this information and could just print it out.

**Comment by kreuzberger** [comment]
> Another possible solution is (this would be the easiest and fastest for now) to produce this at runtime or as a separate target because all information basically available in the internal regestry. The step class holds the data:
> 
> ```c++
> class step
> {
>  public:
>   step(step_callback cb, const std::string& definition)
>       : m_callback(cb), m_definition(definition)
> // ... 
>  private:
>   step_callback m_callback;
>   std::string m_definition; 
>   std::string m_regex_definition;
>   std::vector<token_type> m_value_types;
> };
> ```

i thought of it as an separate parameter: call the executable with an argument and exit without testing or dump it after testing or just before.
I would suggest to get the output as "machine processable" like json/xml format.
maybe `--steps-catalogue=<file>` 
I would call this tool e.g. as a cmake custom target with dependency to the lib/exe with the steps implementation.

**Comment by kreuzberger** [comment]
The only tool i know with same functionality is `behave` with this parameter:
```
--steps-catalog
Show a catalog of all available step definitions. SAME AS: –format=steps.catalog –dry-run –no-summary -q
```

**Comment by ThoSe1990** [comment]
Sounds like a good idea for now 👍 

For now I'd stick to json (where i'd use [nlohman](https://github.com/nlohmann/json)). Are third party dependencies a problem for your local build? 

In short: 
- Print catalog with `--steps-catalog` / `-sc` to a given file or use stdout to print it to the terminal. 
- With printing the step catalog nothings executed we'll return after printing 
- Step types are necessayre (right?) `GIVEN`, `WHEN`, `THEN` (or the general `STEP`) 

As a first draft, would this be enough? (Types I'd list from left to right according to the step definition) 
```
{
  "steps_catalog": [
    {
      "type": "Given/When/Then/Step",
      "definition": "The step definition ",
      "types": ["int", "string", "anonymous", "word", ... ]
    },
.... 

}
```

**Comment by kreuzberger** [comment]
[nlohman](https://github.com/nlohmann/json) is also used by [cucumber-cpp](https://github.com/cucumber/cucumber-cpp) and we have it therefore already as dependency. Question is here HOW you add this as dependency? Just loose with a simple `find_package(nlohmann_json <VERSION?> REQUIRED)`. Currently cucumber-cpp uses 3.10.5 but we provide it as separate conan package, so no issue to use another version here.

**Comment by ThoSe1990** [comment]
I'll integrate it with conan2. This means yes with `find_package(nlohmann_json ..)`, similar as i integrate gtest for my unittests.

**Comment by kreuzberger** [comment]
the draft json should work, i would generate a "human readable" document as an separate build step.
The step definition would include the complete definition, e.g. `"definition": "The box contains {int} item(s)"` with `"types": ["int"]`

**Comment by kreuzberger** [comment]
> yes exactly the definition is just a copy with the cucumber expressions.
> 
> The human readable format would then this:
> 
> ```
> Step Definitions (catalog):
> ----------------------------
> Given A step with {int} and {string}
> When Something happens 
> .... 
> ```
> 
> Two questions remain:
> 
>     1. Does the human readable format need the types explicitly or is it enough since its readable in the step
> 

I think its readable in the step and therefore no types should be needed. Currently custom types are not supported and even then it should be clear from the name 

Should these steps be ordered (subsections)? Background /  GIVEN/WHEN and last all THEN?

>     2. Do you need the file and line to step definition there too? (wouldn't be a big deal to provide this)

No.

> 
> Then I'd implement this:
> 
>     * `--steps-catalog` with an optional file (no file means print to stdout) to produce human readable format
>       
>       * if the file exists we overwrite (i'll check for .feature endings to handle this edge case)
> 
>     * `--steps-catalog-json` same behavior as above but in json format.

ok, maybe affects #41?  --report, --report-json or should we differ action (step-catalog, report) from format?

**Comment by ThoSe1990** [comment]
> ok, maybe affects https://github.com/ThoSe1990/cwt-cucumber/issues/41? --report, --report-json or should we differ action (step-catalog, report) from format?

I don't see a problem here. I treat the args pretty lazy with just a string comparison. So `--step-catalog` and `--step-catalog-json` is quite fine.

**Comment by kreuzberger** [comment]
i would use the json to generate my "manuals", to its up to me to sort it from json. So "order of appearance" is ok for me. Realy important is that just the step definition matches the code and the documentation could then refer it :+1:

**Comment by ThoSe1990** [comment]
yh, fair enough, i forgot you will use it without the main. I'll keep it flexibel

**Comment by ThoSe1990** [comment]
Done https://github.com/ThoSe1990/cwt-cucumber/pull/50

- `--steps-catalog [optional: file]` to print the implemented steps as readable text to stdout or a given file (this does not write to '.feature' files)
- `--steps-catalog-json [optional: file]` to print the implemented steps as json to stdout or a given file (this does not write to '.feature' files)


I left some options to use the catalog when embedding cwt-cucumber. Use the export function in `cwt_cucumber`, like demonstrated in `entry_point`: 

```cpp
  cwt_cucumber cucumber(argc, argv);
// ... 
  if (cucumber.export_catalog())
  {
    return cuke::results::test_status::passed;
  }
```
Export catalog does both, checking if the option was passed in the program arguments and the printing to stdout or a given file. The corresponding output sink (file or stdout) is done when the program arguments are initialized. If you need more flexibility you can use the free functions too:  Checkout `catalog.hpp`: 

```cpp
namespace cuke::catalog
{
[[nodiscard]] std::string as_readable_text();
[[nodiscard]] std::string as_json(std::size_t indents = 2);
void print_readable_text_to_sink();
void print_json_to_sink(std::size_t indents = 2);

}  // namespace cuke::catalog
```

But note: program_options need to be initialized in order to set the sink (default is stdout). This is done by calling the global `program_arguments(argc,argv) and happens in the `cwt_cucumber` constructor.

**Comment by kreuzberger** [comment]
Minor issue: the help shows the text `--step-catalog` while the implementations uses `--steps-catalog`.

**Comment by ThoSe1990** [comment]
ah right, I just fixed this on main branch
