### ISSUE TITLE
Flexible entry point handling

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#48]
If cwt-cucumber is used together with frameworks that use an event queue (we use Qt) its tricky to start the test processing with the single "entry_point" function.

Maybe this could be divided into "parameter parsing" w/o "print help on parameter fail", "test execution" and return. Currently i have to store / pass the argc, argv from my main to the "delayed" call of the entry_point function after starting the Qt event Queue (by execution QtCoreApplication::exec()).

This is internally already done by the cuke_args object which maybe could be used.

**Comment by kreuzberger** [comment]
Yes, this would work out. I am not using the main function in most of my scenarios.
Question here is the argument check. if arguments are invalid, unparsed etc, how can i give an error and print help?

**Comment by ThoSe1990** [comment]
Right now invalid arguments are more or less ignored. 
- Paths which don't exist are ignored
- Options which don't exist ignored too 

I could write a warning to stdout if this helps or we add a `bool valid_args()` function.  Which would then mean: 

```
cwt_cucumber cucumber(argc, argv) 
if (cucumber.args_valid()) 
{
  cucumber.run_tests(); 
  return cucumber.final_result(); 
}
// do custom error handling 
```

To define invalid args: 
- files which don't exist
- options which don't exist
- BUT passing in a directory would not lead to an error (if there aren't feature files in the directory, so be it)

What do you think?

**Comment by kreuzberger** [comment]
The current implementation is good (ignoring). So i have not to ensure that possible arguments for my executable are leading to errors not intended.

**Comment by ThoSe1990** [comment]
PR is open. I added a member function for the help screen in order to avoid unnecessary checks/prints for the overall test result.

`entry_point` demonstrates the use: 

```cpp 
cuke::results::test_status entry_point(int argc, const char* argv[])
{
  cwt_cucumber cucumber(argc, argv);
  if (cucumber.print_help())
  {
    return cuke::results::test_status::passed;
  }
  cucumber.run_tests();
  cucumber.print_results();
  return cucumber.final_result();
}
```

**Comment by ThoSe1990** [comment]
done https://github.com/ThoSe1990/cwt-cucumber/pull/49

FYI, I refactored a few things (structural changes) if something's broken just open an issue.

**Comment by ThoSe1990** [comment]
Quick update, I decided to change the public functions, in order to get all options, this will keep it a bit more flexible in the future (will be updated when i merge the catalog feature): 

```cpp 
cuke::results::test_status entry_point(int argc, const char* argv[])
{
  cwt_cucumber cucumber(argc, argv);
  if (cucumber.get_options().print_help)
  {
    print_help_screen();
    return cuke::results::test_status::passed;
  }
  if (cucumber.get_options().catalog.readable_text)
  {
    cuke::registry().sort_steps_by_type();
    print(cuke::catalog::as_readable_text());
    return cuke::results::test_status::passed;
  }
  cucumber.run_tests();
  cucumber.print_results();
  return cucumber.final_result();
}
```

**Comment by ThoSe1990** [comment]
I changed my mind once more. `cwt_cucumber` has following functions available, I think this gives more flexibility: 

```cpp 
class cwt_cucumber
{
 public:
  cwt_cucumber(int argc, const char* argv[]);
  void run_tests() const noexcept;
  void print_results() const noexcept;
  [[nodiscard]] results::test_status final_result() const noexcept;

  const options& get_options() const noexcept;
  bool print_help() const noexcept;
  bool export_catalog(std::size_t json_indents = 2) const noexcept;
};
```

And see `entry_point` how it can be used: 
```cpp
cuke::results::test_status entry_point(int argc, const char* argv[])
{
  cwt_cucumber cucumber(argc, argv);
  if (cucumber.print_help())
  {
    return cuke::results::test_status::passed;
  }
  if (cucumber.export_catalog())
  {
    return cuke::results::test_status::passed;
  }
  cucumber.run_tests();
  cucumber.print_results();
  return cucumber.final_result();
}
```

if you want to change the indents, just pass the indents to `export_catalog` (`-1` would  remove all indents and linebreaks)

**Comment by ThoSe1990** [comment]
Sure, no rush, just open an issue on any findings
