### ISSUE TITLE
The libraries are always compiled with the static runtime on windows

### ISSUE THREAD

**Issue by mkaes** [ThoSe1990/cwt-cucumber#7]
In the CMakeLists.txt for the MSVC compiler the runtime libraries are alwys overwritten to use the static ones. E.g /MT instead of /MD.

This makes testing of libraries which are not compiled with the static runtime very difficult.
Is there a reason why the runtime is always the static one?
A switch to choose between static and dynamic would be nice.

**Comment by ThoSe1990** [comment]
Good call, haven't thought about that lately. When I work on windows I always use static linking. I'll consider it for future versions.

**Comment by ThoSe1990** [comment]
I removed the hardcoded static runtime build in 1.2.0
