### ISSUE TITLE
DataTables are not yet supported

### ISSUE THREAD

**Issue by mkaes** [ThoSe1990/cwt-cucumber#8]
It seems like data tables are not yet supported.
Changing the example to
`Feature: My first feature
  This is my cucumber-cpp hello world

  Scenario: First Scenario
    Given An empty box
		| item_type |
		| "apple"   |
    When I place 2 x "apple" in it
    Then The box contains 2 item(s)
`
I will get the following error
`[line 6] Error  at '|': Expect StepLine
[line 6] Error  at '|': Expect ScenarioLine
[line 6] Error  at '|': Expect FeatureLine`

The parser should accept this kind of feature files.

**Comment by ThoSe1990** [comment]
Thanks for pointing out, you're correct, data tables aren't supported yet (only Scenario Outlines). Will plan it for next version.

**Comment by mkaes** [comment]
Thanks for the quick response.
I will try it out as soon as I find some time.

**Comment by ThoSe1990** [comment]
I created 1.2.0 and there are examples for tables in `./examples/features/6_tables.feature`. The steps are implemented in `step_definition.cpp`. 

If you encounter a bug or need more accessors to a table, please open another issue. 

Thanks for your feedback. 

Best Thomas
